# Generated by Django 4.0.2 on 2022-02-25 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('documento_text', models.CharField(max_length=15)),
                ('nombre_text', models.CharField(max_length=15)),
                ('apellido_text', models.CharField(max_length=15)),
                ('fecha_nacimiento_date', models.DateTimeField(verbose_name='date published')),
            ],
        ),
    ]
