# Generated by Django 4.0.2 on 2022-03-02 02:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('documento_text', models.CharField(max_length=15, verbose_name='Documentos')),
                ('paciente_nombre_text', models.CharField(default='', max_length=150, verbose_name='Nombre')),
                ('paciente_apellido_text', models.CharField(default='', max_length=150, verbose_name='Apellido')),
                ('paciente_fecha_nacimiento_date', models.DateField(default=datetime.date(2022, 3, 2), verbose_name='Fecha Nacimiento')),
                ('paciente_sexo_enum', models.CharField(choices=[(' ', ' '), ('M', 'Masculino'), ('F', 'Femenino'), ('O', 'Otro')], default=' ', max_length=1, verbose_name='Sexo')),
            ],
        ),
    ]
